import { Artist } from './playlist.interface';

export const favArtists: Artist[] = [
  {
    id: 1,
    name: 'Juice WRLD',
    bio: 'Emo-rap icon blending raw emotion, melodic flows, and tragic storytelling.',
    image: 'assets/images/artists/juice.webp',
    audioUrl: 'assets/audios/11.m4a',
    genre: 'Emo Rap',
    gradient: 'from-purple-500 via-indigo-500 to-pink-500',
    color: '#a855f7',
    track: 'Lucid Dreams',
  },

  {
    id: 2,
    name: 'Shawn Mendes',
    bio: 'Pop heartthrob known for emotionally charged lyrics and catchy guitar-driven tracks.',
    image: 'assets/images/artists/shawn.webp',
    audioUrl: 'assets/audios/chemical.m4a',
    genre: 'Pop Rock',
    gradient: 'from-blue-400 via-purple-500 to-purple-600',
    color: '#6366f1',
    track: 'Treat You Better',
  },
  {
    id: 3,
    name: 'Maroon 5',
    bio: 'Mainstream pop-rock with funky undertones and chart-topping hooks.',
    image: 'assets/images/artists/adam.webp',
    audioUrl: 'assets/audios/11.m4a',
    genre: 'Pop Rock',
    gradient: 'from-pink-400 via-indigo-500 to-purple-500',
    color: '#d946ef',
    track: 'Beautiful Mistake',
  },
  {
    id: 4,
    name: 'Post Malone',
    bio: 'Genre-blending artist with laid-back delivery and emo-influenced rap-pop.',
    image: 'assets/images/artists/post.webp',
    audioUrl: 'assets/audios/chemical.m4a',
    genre: 'Hip-Hop / Pop',
    gradient: 'from-yellow-400 via-red-400 to-pink-500',
    color: '#f59e0b',
    track: 'Chemical',
  },
  {
    id: 5,
    name: 'Ali Gatie',
    bio: 'Emotionally vulnerable R&B pop artist focused on heartbreak and introspection.',
    image: 'assets/images/artists/ali.webp',
    audioUrl: 'assets/audios/11.m4a',
    genre: 'Pop R&B',
    gradient: 'from-green-300 via-emerald-400 to-teal-500',
    color: '#10b981',
    track: 'Moonlight',
  },
  {
    id: 6,
    name: 'Charlie Puth',
    bio: 'Master of slick pop production, catchy hooks, and falsetto-laced vocals.',
    image: 'assets/images/artists/charlie.webp',
    audioUrl: 'assets/audios/11.m4a',
    genre: 'Pop',
    gradient: 'from-red-500 via-yellow-500 to-orange-500',
    color: '#ef4444',
    track: 'Cheating on You',
  },
  {
    id: 7,
    name: 'Drake',
    bio: 'Rap’s emotional powerhouse blending introspection with viral anthems.',
    image: 'assets/images/artists/drake.webp',
    audioUrl: 'assets/audios/11.m4a',
    genre: 'Hip-Hop',
    gradient: 'from-gray-600 via-gray-700 to-black',
    color: '#4b5563',
    track: 'Toosie Slide',
  },
  {
    id: 8,
    name: 'Ed Sheeran',
    bio: 'Singer-songwriter legend mixing acoustic soul with radio-ready pop ballads.',
    image: 'assets/images/artists/ed_sheeran.webp',
    audioUrl: 'assets/audios/11.m4a',
    genre: 'Pop / Folk',
    gradient: 'from-orange-400 via-pink-400 to-purple-500',
    color: '#fb923c',
    track: 'Bad Habits',
  },
  {
    id: 9,
    name: 'J. Cole',
    bio: 'Lyrical storyteller known for conscious rap and real-world reflections.',
    image: 'assets/images/artists/j_cole.webp',
    audioUrl: 'assets/audios/11.m4a',
    genre: 'Conscious Rap',
    gradient: 'from-cyan-400 via-blue-500 to-indigo-600',
    color: '#22d3ee',
    track: 'Middle Child',
  },
  {
    id: 10,
    name: 'One Direction',
    bio: 'British boy band sensation delivering pop anthems with infectious energy.',
    image: 'assets/images/artists/one_direction.webp',
    audioUrl: 'assets/audios/11.m4a',
    genre: 'Pop',
    gradient: 'from-pink-300 via-rose-400 to-red-500',
    color: '#f472b6',
    track: 'What Makes You Beautiful',
  },
  {
    id: 11,
    name: 'Keshi',
    bio: 'Alt-R&B singer blending lo-fi textures, sad boy energy, and silky vocals.',
    image: 'assets/images/artists/keshi.webp',
    audioUrl: 'assets/audios/chemical.m4a',
    genre: 'Lo-fi R&B',
    gradient: 'from-yellow-300 via-orange-400 to-red-500',
    color: '#facc15',
    track: 'Skeletons',
  },
  {
    id: 12,
    name: 'The Weeknd',
    bio: 'Synth-laced anthems blending darkness, desire, and retro 80s vibes.',
    image: 'assets/images/artists/the_weeked.webp',
    audioUrl: 'assets/audios/chemical.m4a',
    genre: 'Synthwave / R&B',
    gradient: 'from-gray-300 via-gray-500 to-black',
    color: '#9ca3af',
    track: 'Die for You',
  },
];
