import { Artist } from './playlist.interface';

export const favArtists: Artist[] = [
  {
    id: 1,
    name: 'Juice WRLD',
    bio: `'Truth No Dare' captures Juice WRLD’s raw, emotional storytelling — a reflection of inner battles and vulnerability.`,
    image: 'assets/images/artists/juice.webp',
    audioUrl: 'assets/audios/Truth_No_Dare.mp3',
    genre: 'Emo Rap',
    track: 'Truth No Dare (Unreleased)',
  },
  {
    id: 2,
    name: 'Shawn Mendes',
    bio: `'Treat You Better' is a heartfelt promise wrapped in Shawn Mendes’ signature pop-rock ballad style.`,
    image: 'assets/images/artists/shawn.webp',
    audioUrl: 'assets/audios/Treat_You_Better.mp3',
    genre: 'Pop Rock',
    track: 'Treat You Better',
  },
  {
    id: 3,
    name: 'Maroon 5',
    bio: `'Beautiful Mistake' explores the bittersweet pain of love gone wrong — classic Maroon 5 heartbreak vibes.`,
    image: 'assets/images/artists/adam.webp',
    audioUrl: 'assets/audios/Beautiful_mistake.mp3',
    genre: 'Pop Rock',
    track: 'Beautiful Mistake',
  },
  {
    id: 4,
    name: 'Post Malone',
    bio: `'Chemical' blends Post Malone’s hazy vocals with emotional dependency and toxic love loops.`,
    image: 'assets/images/artists/post.webp',
    audioUrl: 'assets/audios/Chemical.mp3',
    genre: 'Hip-Hop / Pop',
    track: 'Chemical',
  },
  {
    id: 5,
    name: 'Ali Gatie',
    bio: `'Moonlight' reflects Ali Gatie’s signature emotional depth, singing about longing and late-night heartbreak.`,
    image: 'assets/images/artists/ali.webp',
    audioUrl: 'assets/audios/Moonlight.mp3',
    genre: 'Pop R&B',
    track: 'Moonlight',
  },
  {
    id: 6,
    name: 'Charlie Puth',
    bio: `'Cheating on You' hits with a twist — it's not what it sounds like. Charlie dives into emotional conflict with a smooth vibe.`,
    image: 'assets/images/artists/charlie.webp',
    audioUrl: 'assets/audios/Cheating_on_You.mp3',
    genre: 'Pop',
    track: 'Cheating on You',
  },
  {
    id: 7,
    name: 'Drake',
    bio: `'Toosie Slide' mixes viral dance culture with Drake’s signature laid-back flex and smooth delivery.`,
    image: 'assets/images/artists/drake.webp',
    audioUrl: 'assets/audios/Toosie_Slide.mp3',
    genre: 'Hip-Hop',
    track: 'Toosie Slide',
  },
  {
    id: 8,
    name: 'Ed Sheeran',
    bio: `'Sharp of You' dives into emotional honesty, blending acoustic vibes with Ed Sheeran's raw storytelling.`,
    image: 'assets/images/artists/ed_sheeran.webp',
    audioUrl: 'assets/audios/Sharp_of_you.mp3',
    genre: 'Pop / Folk',
    track: 'Sharp of You',
  },
  {
    id: 9,
    name: 'J. Cole',
    bio: `'Middle Child' is J. Cole’s declaration of his place in rap — the bridge between legends and the new wave.`,
    image: 'assets/images/artists/j_cole.webp',
    audioUrl: 'assets/audios/Middle_child.mp3',
    genre: 'Conscious Rap',
    track: 'Middle Child',
  },
  {
    id: 10,
    name: 'One Direction',
    bio: `'What Makes You Beautiful' is pure pop magic — a feel-good anthem about appreciating someone’s natural charm.`,
    image: 'assets/images/artists/one_direction.webp',
    audioUrl: 'assets/audios/What_Makes_You_Beautiful.mp3',
    genre: 'Pop',
    track: 'What Makes You Beautiful',
  },
  {
    id: 11,
    name: 'Keshi',
    bio: `'Skeletons' dives into the haunting emotions of past relationships with Keshi’s lo-fi melancholy tone.`,
    image: 'assets/images/artists/keshi.webp',
    audioUrl: 'assets/audios/Skeletons.mp3',
    genre: 'Lo-fi R&B',
    track: 'Skeletons',
  },
  {
    id: 12,
    name: 'The Weeknd',
    bio: `'Die for You' is The Weeknd’s emotional confession of undying love over synth-heavy, retro production.`,
    image: 'assets/images/artists/the_weeked.webp',
    audioUrl: 'assets/audios/Die_For_You.mp3',
    genre: 'Synthwave / R&B',
    track: 'Die for You',
  },
  {
    id: 13,
    name: 'Bruno Mars',
    bio: `'Marry You' is a spontaneous love anthem — Bruno Mars at his most playful and romantic.`,
    image: 'assets/images/artists/bruno.webp',
    audioUrl: 'assets/audios/Marry_You.mp3',
    genre: 'Synthwave / R&B',
    track: 'Marry You',
  },
];
