import { Artist } from './playlist.interface';

export const favArtists: Artist[] = [
  {
    id: 1,
    name: 'Aurora',
    bio: 'Ethereal pop with mystical undertones that transport listeners to otherworldly realms.',
    image: 'assets/images/artists/juice.png',
    audioUrl: 'assets/audios/11.m4a',
    genre: 'Ethereal Pop',
    gradient: 'from-purple-400 via-pink-500 to-red-500',
    color: '#8b5cf6',
  },
  {
    id: 2,
    name: 'Joji',
    bio: 'Lo-fi R&B artist crafting melancholic soundscapes with introspective lyrics.',
    image: 'assets/images/artists/shawn.png',
    audioUrl: 'assets/audios/chemical.m4a',
    genre: 'Alternative R&B',
    gradient: 'from-blue-400 via-purple-500 to-purple-600',
    color: '#6366f1',
  },
  {
    id: 3,
    name: 'Grimes',
    bio: 'Synth-heavy cyber-pop mixing glitch, art, and futuristic themes.',
    image: 'assets/images/artists/adam.png',
    audioUrl: 'assets/audios/11.m4a',
    genre: 'Cyber Pop',
    gradient: 'from-pink-400 via-indigo-500 to-purple-500',
    color: '#d946ef',
  },
  {
    id: 4,
    name: 'Tame Impala',
    bio: 'Psychedelic rock meets electronic vibes in atmospheric soundscapes.',
    image: 'assets/images/artists/post.png',
    audioUrl: 'assets/audios/chemical.m4a',
    genre: 'Psychedelic Rock',
    gradient: 'from-yellow-400 via-red-400 to-pink-500',
    color: '#f59e0b',
  },
  {
    id: 5,
    name: 'Billie Eilish',
    bio: 'Dark pop with minimalist production and haunting vocals.',
    image: 'assets/images/artists/ali.png',
    audioUrl: 'assets/audios/11.m4a',
    genre: 'Dark Pop',
    gradient: 'from-green-300 via-emerald-400 to-teal-500',
    color: '#10b981',
  },
  {
    id: 6,
    name: 'The Weeknd',
    bio: 'Retro-futuristic synth pop with cinematic vibes and moody vocals.',
    image: 'assets/images/artists/charlie.png',
    audioUrl: 'assets/audios/11.m4a',
    genre: 'Synth Pop',
    gradient: 'from-red-500 via-yellow-500 to-orange-500',
    color: '#ef4444',
  },
  {
    id: 7,
    name: 'Arctic Monkeys',
    bio: 'British indie rock fused with post-punk and suave lyricism.',
    image: 'assets/images/artists/drake.webp',
    audioUrl: 'assets/audios/11.m4a',
    genre: 'Indie Rock',
    gradient: 'from-gray-600 via-gray-700 to-black',
    color: '#4b5563',
  },
  {
    id: 8,
    name: 'SZA',
    bio: 'Neo-soul and R&B grooves wrapped in emotional vulnerability.',
    image: 'assets/images/artists/ed_sheeran.png',
    audioUrl: 'assets/audios/11.m4a',
    genre: 'Neo-Soul',
    gradient: 'from-orange-400 via-pink-400 to-purple-500',
    color: '#fb923c',
  },
  {
    id: 9,
    name: 'Frank Ocean',
    bio: 'Genre-bending artist delivering raw emotion through lush soundscapes.',
    image: 'assets/images/artists/j_cole.png',
    audioUrl: 'assets/audios/11.m4a',
    genre: 'Experimental R&B',
    gradient: 'from-cyan-400 via-blue-500 to-indigo-600',
    color: '#22d3ee',
  },
  {
    id: 10,
    name: 'Lana Del Rey',
    bio: 'Melancholy ballads with cinematic storytelling and nostalgic vibes.',
    image: 'assets/images/artists/one_direction.png',
    audioUrl: 'assets/audios/11.m4a',
    genre: 'Dream Pop',
    gradient: 'from-pink-300 via-rose-400 to-red-500',
    color: '#f472b6',
  },
  {
    id: 11,
    name: 'Tyler, The Creator',
    bio: 'Unfiltered creativity mixing rap, funk, and soul.',
    image: 'assets/images/artists/keshi.png',
    audioUrl: 'assets/audios/chemical.m4a',
    genre: 'Experimental Hip-Hop',
    gradient: 'from-yellow-300 via-orange-400 to-red-500',
    color: '#facc15',
  },
  {
    id: 12,
    name: 'FKA twigs',
    bio: 'Avant-garde pop artist pushing boundaries with haunting vocals and sharp visuals.',
    image: 'assets/images/artists/the_weeked.png',
    audioUrl: 'assets/audios/chemical.m4a',
    genre: 'Avant-Pop',
    gradient: 'from-gray-300 via-gray-500 to-black',
    color: '#9ca3af',
  },
];
